name: docker image to ghcr

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
  schedule: 
   - cron: '0 0 * * 0'

jobs:
  Clone:
    strategy:
      fail-fast: false
      matrix:
        image:
        - tonistiigi/binfmt
        - moby/buildkit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v5
    - uses: imjasonh/setup-crane@v0.4
    - run: |
        for tag in $(crane ls ${{ matrix.image }}); do
          crane copy ${{ matrix.image }}:$tag ghcr.io/${{ github.repository_owner }}/$(echo ${{ matrix.image }} | cut -d'/' -f2 | cut -d':' -f1):$tag
        done
