name: docker image to ghcr

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:

jobs:
  Clone:
    strategy:
      matrix:
        image:
        - tonistiigi/binfmt
        - moby/buildkit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v5
    - uses: imjasonh/setup-crane@v0.4
    - run: |
        tags=$(crane ls ${{ matrix.image }})
        for tag in $tags; do
          crane copy ${{ matrix.image }}:$tag ghcr.io/${{ github.repository_owner }}/$(echo ${{ matrix.image }} | cut -d'/' -f2 | cut -d':' -f1):$tag
        done
